import { useState, useEffect } from 'react';
import './App.css';

const INDUSTRIES = [
  "Technology", "Healthcare", "Finance", "Education", 
  "Retail", "Real Estate", "Legal", "Marketing"
];

const AGENTS = [
  { 
    name: "Analyst Agent", 
    role: "Researching market data...", 
    description: "Deep dive into industry trends and competitive landscape." 
  },
  { 
    name: "Strategist Agent", 
    role: "Building strategies...", 
    description: "Transforming insights into actionable business goals." 
  },
  { 
    name: "Summarizer Agent", 
    role: "Writing executive brief...", 
    description: "Distilling complex data into high-level briefings." 
  }
];

function App() {
  const [state, setState] = useState('input'); // 'input', 'loading', 'results', 'error'
  const [topic, setTopic] = useState('');
  const [industry, setIndustry] = useState(INDUSTRIES[0]);
  const [loadingAgentIdx, setLoadingAgentIdx] = useState(0);
  const [results, setResults] = useState(null);
  const [activeTab, setActiveTab] = useState('summary');
  const [errorMsg, setErrorMsg] = useState('');

  // Loading animation logic
  useEffect(() => {
    let interval;
    if (state === 'loading') {
      interval = setInterval(() => {
        setLoadingAgentIdx((prev) => (prev + 1) % AGENTS.length);
      }, 3000);
    }
    return () => clearInterval(interval);
  }, [state]);

  const handleRunAnalysis = async () => {
    setState('loading');
    setLoadingAgentIdx(0);
    setErrorMsg('');
    
    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:8000'}/analyze`,{
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic, industry }),
      });
      
      if (!response.ok) {
        throw new Error('Analysis failed — try again');
      }
      
      const data = await response.json();
      setResults(data);
      setState('results');
    } catch (error) {
      setErrorMsg(error.message || 'Analysis failed — try again');
      setState('error');
    }
  };

  const downloadReport = () => {
    const text = `
-----------------------------------------
BUSINESS INTELLIGENCE REPORT
TOPIC: ${results.topic}
INDUSTRY: ${results.industry}
-----------------------------------------

EXECUTIVE SUMMARY
=================
${results.summary}

FULL ANALYSIS
=============
${results.analysis}

STRATEGIES
==========
${results.strategies}

Generated by AI Business Intelligence Agent
-----------------------------------------
    `.trim();
    
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${results.topic.toLowerCase().replace(/\s+/g, '-')}-intelligence-report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const shareSummary = () => {
    const text = `Executive Summary for ${results.topic} (${results.industry}):\n\n${results.summary}`;
    navigator.clipboard.writeText(text);
    alert('Executive summary copied to clipboard!');
  };

  const copyToClipboard = () => {
    const text = `
TOPIC: ${results.topic}
INDUSTRY: ${results.industry}

EXECUTIVE SUMMARY:
${results.summary}

FULL ANALYSIS:
${results.analysis}

STRATEGIES:
${results.strategies}
    `.trim();
    
    navigator.clipboard.writeText(text);
    alert('Full report copied to clipboard!');
  };

  if (state === 'input' || state === 'error') {
    return (
      <div className="card">
        <h1 style={{ color: 'var(--accent-color)', marginBottom: '0.5rem' }}>Business Intelligence Agent</h1>
        <p style={{ color: 'var(--text-dim)', marginBottom: '2rem' }}>3 AI agents working together</p>

        {state === 'error' && (
          <div style={{ 
            backgroundColor: '#450a0a', 
            border: '1px solid #ef4444', 
            color: '#fca5a5', 
            padding: '12px', 
            borderRadius: '4px', 
            marginBottom: '1.5rem',
            fontSize: '0.9rem',
            textAlign: 'center'
          }}>
            {errorMsg}
          </div>
        )}

        <div style={{ marginBottom: '1.5rem' }}>
          <label style={{ display: 'block', marginBottom: '8px', fontSize: '0.9rem' }}>Topic</label>
          <input 
            type="text" 
            placeholder="e.g. AI-powered HR software" 
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
          />
        </div>

        <div style={{ marginBottom: '2rem' }}>
          <label style={{ display: 'block', marginBottom: '8px', fontSize: '0.9rem' }}>Industry</label>
          <select value={industry} onChange={(e) => setIndustry(e.target.value)}>
            {INDUSTRIES.map(ind => <option key={ind} value={ind}>{ind}</option>)}
          </select>
        </div>

        <button 
          onClick={handleRunAnalysis}
          disabled={!topic}
          style={{
            backgroundColor: 'var(--accent-color)',
            color: 'var(--bg-color)',
            border: 'none',
            padding: '16px',
            fontSize: '1rem',
            fontWeight: 'bold',
            width: '100%',
            borderRadius: '4px',
            marginBottom: '1.5rem',
            opacity: !topic ? 0.5 : 1
          }}
        >
          Run Analysis
        </button>

        <div style={{ display: 'flex', justifyContent: 'center', gap: '10px' }}>
          <span className="pill">Analyst</span>
          <span style={{ color: 'var(--text-dim)' }}>→</span>
          <span className="pill">Strategist</span>
          <span style={{ color: 'var(--text-dim)' }}>→</span>
          <span className="pill">Summarizer</span>
        </div>
      </div>
    );
  }

  if (state === 'loading') {
    const agent = AGENTS[loadingAgentIdx];
    return (
      <div className="card" style={{ textAlign: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '20px' }}>
          <div className="pulsing-dot"></div>
          <h2 style={{ color: 'var(--accent-color)' }}>{agent.name}</h2>
        </div>
        <p style={{ fontSize: '1.2rem', marginBottom: '10px' }}>{agent.role}</p>
        <p style={{ color: 'var(--text-dim)', fontSize: '0.9rem' }}>{agent.description}</p>
        
        <div style={{ marginTop: '40px', display: 'flex', justifyContent: 'center', gap: '10px' }}>
          {AGENTS.map((_, i) => (
            <div 
              key={i} 
              style={{ 
                width: '40px', 
                height: '4px', 
                backgroundColor: i === loadingAgentIdx ? 'var(--accent-color)' : 'var(--border-color)',
                transition: 'background-color 0.3s ease'
              }}
            />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="results-container">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '30px' }}>
        <div>
          <h1 style={{ color: 'var(--accent-color)', fontSize: '1.5rem' }}>{results.topic}</h1>
          <p style={{ color: 'var(--text-dim)' }}>{results.industry} Industry Analysis</p>
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px', justifyContent: 'flex-end', maxWidth: '400px' }}>
          <button 
            onClick={shareSummary}
            style={{ padding: '8px 16px', borderRadius: '4px', border: '1px solid var(--border-color)', background: 'transparent', color: 'var(--text-main)', fontSize: '0.9rem' }}
          >
            Share Summary
          </button>
          <button 
            onClick={copyToClipboard}
            style={{ padding: '8px 16px', borderRadius: '4px', border: '1px solid var(--border-color)', background: 'transparent', color: 'var(--text-main)', fontSize: '0.9rem' }}
          >
            Copy Full
          </button>
          <button 
            onClick={downloadReport}
            style={{ padding: '8px 16px', borderRadius: '4px', border: '1px solid var(--border-color)', background: 'transparent', color: 'var(--text-main)', fontSize: '0.9rem' }}
          >
            Download .txt
          </button>
          <button 
            onClick={() => setState('input')}
            style={{ padding: '8px 16px', borderRadius: '4px', border: 'none', background: 'var(--accent-color)', color: 'var(--bg-color)', fontWeight: 'bold', fontSize: '0.9rem' }}
          >
            New Analysis
          </button>
        </div>
      </div>

      <div className="tabs">
        <button 
          className={`tab ${activeTab === 'summary' ? 'active' : ''}`}
          onClick={() => setActiveTab('summary')}
        >
          Executive Summary
        </button>
        <button 
          className={`tab ${activeTab === 'analysis' ? 'active' : ''}`}
          onClick={() => setActiveTab('analysis')}
        >
          Full Analysis
        </button>
        <button 
          className={`tab ${activeTab === 'strategies' ? 'active' : ''}`}
          onClick={() => setActiveTab('strategies')}
        >
          Strategies
        </button>
      </div>

      <div className="card" style={{ maxWidth: 'none', marginBottom: '20px' }}>
        <div className="whitespace-pre">
          {activeTab === 'summary' && results.summary}
          {activeTab === 'analysis' && results.analysis}
          {activeTab === 'strategies' && results.strategies}
        </div>
      </div>

      <div style={{ textAlign: 'center', color: 'var(--text-dim)', fontSize: '0.8rem', marginTop: '40px' }}>
        Powered by 3 AI Agents ⚡
      </div>
    </div>
  );
}

export default App;
